/*
 * TemperatureMonitoringSystem_Cfg.h
 *
 *  Created on: Jul 22, 2023
 *      Author: Abdu
 */

#ifndef SYSTEMLAYERS_APP_TEMPERATUREMONITORINGSYSTEM_TEMPERATUREMONITORINGSYSTEM_CFG_H_
#define SYSTEMLAYERS_APP_TEMPERATUREMONITORINGSYSTEM_TEMPERATUREMONITORINGSYSTEM_CFG_H_


#define TEMPERATURE_THRESHOLD  125


#endif /* SYSTEMLAYERS_APP_TEMPERATUREMONITORINGSYSTEM_TEMPERATUREMONITORINGSYSTEM_CFG_H_ */
