/*
 * TemperatureGlobalData.h
 *
 *  Created on: Jul 22, 2023
 *      Author: Abdu
 */

#ifndef SYSTEMLAYERS_APP_TEMPERATUREMONITORINGSYSTEM_TEMPERATURESENSOR_TEMPERATUREGLOBALDATA_H_
#define SYSTEMLAYERS_APP_TEMPERATUREMONITORINGSYSTEM_TEMPERATURESENSOR_TEMPERATUREGLOBALDATA_H_

static uint32 TemperatureValue_g = 0;




#endif /* SYSTEMLAYERS_APP_TEMPERATUREMONITORINGSYSTEM_TEMPERATURESENSOR_TEMPERATUREGLOBALDATA_H_ */
